# settings from whitehouse.github.io/fitara

#document settings
title: Management and Oversight of Information Technology Resources
desc: Proposed Guidance From the Office of Management and Budget (OMB)
url: https://whitehouse.github.io/fitara/

#global settings, no need to change these
root_url: https://whitehouse.github.io/fitara/
production_hostname: whitehouse.github.io
org_name: whitehouse
repo_name: fitara
branch: gh-pages

# default build settings for running locally, no need to edit
pymgemnts: true
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
markdown: kramdown
relative_permalinks: false

gems:
  - jekyll-redirect-from

kramdown:
  toc_levels: "1,2"

# original settings

permalink: pretty
# markdown: rdiscount
highlighter: pygments
# url: https://management.cio.gov

collections:
  - guidanceSections

sass:
    sass_dir: assets/_sass
